apiVersion: v1
kind: Node
metadata:
  annotations:
    kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/cri-dockerd.sock
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-08-01T18:37:04Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: minikube
    kubernetes.io/os: linux
    minikube.k8s.io/commit: 5883c09216182566a63dff4c326a6fc9ed2982ff
    minikube.k8s.io/name: minikube
    minikube.k8s.io/primary: "true"
    minikube.k8s.io/updated_at: 2024_08_02T02_37_07_0700
    minikube.k8s.io/version: v1.33.1
    node-role.kubernetes.io/control-plane: ""
    node.kubernetes.io/exclude-from-external-load-balancers: ""
  name: minikube
  resourceVersion: "375330"
  uid: 1b1d0600-7898-44ec-bbae-fab2577fb5f2
spec:
  podCIDR: 10.244.0.0/24
  podCIDRs:
    - 10.244.0.0/24
status:
  addresses:
    - address: 192.168.49.2
      type: InternalIP
    - address: minikube
      type: Hostname
  allocatable:
    cpu: "8"
    ephemeral-storage: 1055762868Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8024096Ki
    pods: "110"
  capacity:
    cpu: "8"
    ephemeral-storage: 1055762868Ki
    hugepages-1Gi: "0"
    hugepages-2Mi: "0"
    memory: 8024096Ki
    pods: "110"
  conditions:
    - lastHeartbeatTime: "2024-09-21T13:26:43Z"
      lastTransitionTime: "2024-08-01T18:37:00Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2024-09-21T13:26:43Z"
      lastTransitionTime: "2024-08-01T18:37:00Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2024-09-21T13:26:43Z"
      lastTransitionTime: "2024-08-01T18:37:00Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2024-09-21T13:26:43Z"
      lastTransitionTime: "2024-08-01T18:37:06Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
    - names:
        - nginx@sha256:447a8665cc1dab95b1ca778e162215839ccbb9189104c79d7ec3a81e14577add
        - nginx:latest
      sizeBytes: 187694648
    - names:
        - nginx@sha256:6af79ae5de407283dcea8b00d5c37ace95441fd58a8b1d2aa1ed93f5511bb18c
      sizeBytes: 187603368
    - names:
        - registry.k8s.io/etcd@sha256:44a8e24dcbba3470ee1fee21d5e88d128c936e9b55d4bc51fbef8086f8ed123b
        - registry.k8s.io/etcd:3.5.12-0
      sizeBytes: 149347661
    - names:
        - registry.k8s.io/kube-apiserver@sha256:6b8e197b2d39c321189a475ac755a77896e34b56729425590fbc99f3a96468a3
        - registry.k8s.io/kube-apiserver:v1.30.0
      sizeBytes: 116552324
    - names:
        - registry.k8s.io/kube-controller-manager@sha256:5f52f00f17d5784b5ca004dffca59710fa1a9eec8d54cebdf9433a1d134150fe
        - registry.k8s.io/kube-controller-manager:v1.30.0
      sizeBytes: 111113187
    - names:
        - registry.k8s.io/kube-proxy@sha256:ec532ff47eaf39822387e51ec73f1f2502eb74658c6303319db88d2c380d0210
        - registry.k8s.io/kube-proxy:v1.30.0
      sizeBytes: 84675401
    - names:
        - registry.k8s.io/kube-scheduler@sha256:2353c3a1803229970fcb571cffc9b2f120372350e01c7381b4b650c4a02b9d67
        - registry.k8s.io/kube-scheduler:v1.30.0
      sizeBytes: 61969366
    - names:
        - registry.k8s.io/coredns/coredns@sha256:1eeb4c7316bacb1d4c8ead65571cd92dd21e27359f0d4917f1a5822a73b75db1
        - registry.k8s.io/coredns/coredns:v1.11.1
      sizeBytes: 59820619
    - names:
        - gcr.io/k8s-minikube/storage-provisioner@sha256:18eb69d1418e854ad5a19e399310e52808a8321e4c441c1dddad8977a0d7a944
        - gcr.io/k8s-minikube/storage-provisioner:v5
      sizeBytes: 31465472
    - names:
        - registry.k8s.io/pause@sha256:7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097
        - registry.k8s.io/pause:3.9
      sizeBytes: 743952
  nodeInfo:
    architecture: amd64
    bootID: 4d37fc17-abc5-408b-964f-abc33ddc8683
    containerRuntimeVersion: docker://26.1.1
    kernelVersion: 5.15.153.1-microsoft-standard-WSL2
    kubeProxyVersion: v1.30.0
    kubeletVersion: v1.30.0
    machineID: 7b97dfc3d07348c4b6a7e2880f479c09
    operatingSystem: linux
    osImage: Ubuntu 22.04.4 LTS
    systemUUID: 7b97dfc3d07348c4b6a7e2880f479c09
