apiVersion: v1
kind: Pod
metadata:
  name: playground
spec:
  containers:
    - name: playground
      image: nginx:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
