apiVersion: v1
kind: Pod
metadata:
  name: ssh-server
  labels:
    name: ssh-server
spec:
  containers:
    - name: ssh-server
      image: ssh-server:v2
      imagePullPolicy: Never
      command: ["sleep", "infinity"]
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 22
        - containerPort: 2200
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-server
spec:
  selector:
    name: ssh-server
  type: NodePort
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: ssh-2200
      port: 2200
      targetPort: 2200
